# Generated by Django 6.0.5 on 2026-05-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tittle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('movie', 'Filme'), ('series', 'Série')], max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('realese_year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
